### ISSUE TITLE
SB: Killing Rats is not a crime

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#266]
Killing Rats Isn't a Crime
To make things a little more complex, there are a (very few) cases where townspeople and monsters reside on the same map. If you use the blanket logic of "killing in a town is murder" then that won't be completley correct. In Yew, there's rats in the basement you can kill to no ill effect on karma/townsfolk. I think also if you kill the gargoyles in BT's castle (or more likely put on invis. rings and make them flee cause those are probably the hardest enemies in the game) nobody gets mad at you as I recall.

I think there's also a few of the small village maps that have rats or other monsters; none of these count as murder.

There's one map where there is a talking rat, and one map where there is a talking demon (actually there's at least a couple maps with talking demons). I'm not sure if killing these things count as murder. One of these demons (the one in the keep where you get the well) attacks you no matter what happens, so that one might just be a regular monster with a 'starts a conversation' trigger on it, as opposed to the demon who lives in a hut in the desert who is 100% friendly.

Notoriously there's some kids in a dungeon that you can kill. Dungeon murders never impact karma as I recall.

You could probably use the blanket logic of 'if something attacks YOU, it isn't murder' since I think that may be closer to the truth? For example, in LB's castle there are prisoners in the basement that, if freed, will attack you and they don't anger anyone. I think there's also a fighter somewhere that, if you talk to him, he's like "leave me alone" and if you keep talking to him he'll eventually fight you -- I don't know if that counts as murder or not (... my recollection is that it DID count as murder in that case).

Ack this is rambling and I'm feeling like its not very helpful because I'm using "somewhere" and "as I recall" a little too often :) But there's a lot of facets to what is actually 'murder' in this game, just like in RL. :D

@tanabi

**Comment by tanabi** [comment]
I was reading these and noticed a typo:

One of these demons (the one in the keep where you get the well) attacks you no matter what happens, so that one might just be a regular monster with a 'starts a conversation' trigger on it, as opposed to the demon who lives in a hut in the desert who is 100% friendly.

Where you get the "well" makes no sense.  It's actually the demon in the place where you get the BADGE of the oppression.  This demon guards the front door and you have to kill him.  He asks you a riddle, and the answer to the riddle is 'well' which is why I wrote 'well' there, but whether or not you get that right he attacks you.

I think, therefore, he's an aggressive monster that has a conversation trigger that happens before he can attack you; thus, no matter how you end the conversation, he attacks you.  These weird little behaviors are part of why I love U5 so much :)

**Comment by cambragol** [comment]
I had this debate too for Threat of the Trinity! I added a lot of 'creatures' to new and old maps.

My solution was killing any creature who cannot 'speak' is not a crime. Killing creatures that have a dialogue is a crime.

I don't know if that helps you, but there it is.

**Comment by tanabi** [comment]
@cambragol Cool.  I totally want to feel your feelies, too.  I didn't know about your project but I'll definitely be watching it now :)

**Comment by cambragol** [comment]
@tanabi Awesome! The more who are interested the more likely it will be come reality.

Also, nice work on identifying all these Ultima V quirks. Definitely they are little things that make the game special. In fact, I think it is the little things, like these, that keep the game 'mysterious' and lend to its depth, because players are never (or less likely) to understand the system. These quirks throw monkey wrenches into their understanding of the 'system' of the game, and as long as the 'system' is not fully grasped, the game remains interesting.

**Comment by bradhannah** [comment]
Good details. Here is what I know so far...
"Balinor" is the daemon in StoneGate who gives you riddle. His default AI is fixed and doesn't indicate he will chat on his own - this typically means it's a special case AI (there are so many!)

Technically when you fail the riddle or refuse to answer he "calls the guards". Typically with other Daemons, this means he attacks immediately. In this case he doesn't know he is a guard lol

Still digging in, but will require some custom stuff for sure.

**Comment by bradhannah** [comment]
Yup, as expected he has "Custom AI" which is a common flag when it would have called some special handling code in game. Now I need to dig in and observe the original behaviour closely and see if I have an AI type already defined for it. I suspect it's the same as the aggressive guards who tries to intersect with you and "talk"

**Comment by bradhannah** [comment]
Okay, think I have this down now. Because of the Custom AI flag - I have been able to identify hostile mobs. So that covers the easy ones like Rats. 

The more complicated ones like Drudgeworth in the basement of LBs are covered too. His AI basically says, speak if spoke to -but if he can reach the Avatar then attack! Since the Avatar isn't initiating, then no karma loss. 

The daemons at Windmere are interesting! Basically there is a "wanted by guards", which I can "wanted to by PoPo". There AI is called FixedExceptAttackeWhenIsWantedByThePoPo (a mouthful) - but basically if someone rings the alarm bells then they switch from standing in place, to attacking me! So if you attack them, loss Karma, if they attack you - no karma loss.

Thanks for all the guidance above - there may be more corner cases, but this largely covers it.
